version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: planning_backend
    command: yarn start
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
      - ./backend/data:/backend/data
    restart: no
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: planning_frontend
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    restart: no
